language: cpp

# run cmake to generate the Makefile, then run make
# run on linux amd64 and arm64
compiler:
  - clang
  - gcc

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.23/cmake-3.23.0-linux-x86_64.sh
  - chmod +x cmake-3.23.0-linux-x86_64.sh
  - ./cmake-3.23.0-linux-x86_64.shchm --prefix=$HOME/usr --exclude-subdir --skip-license

script:
  - cd executionbackup-cpp
  - cmake .
  - make

